apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: external-nginx
  rules:
  - host: express.familygiftme.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express
            port:
              name: http
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: express
            port:
              name: http