apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app
spec:
  ingressClassName: nginx 
  rules:
  - host: my-app.com
    http:
      paths:
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 80
