controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"
  ingressClass: external-nginx
  ingressClassResource:
    enabled: true 
    default: true 
  replicaCount: 1
  admissionWebHooks: 
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

